API_KEY = ''
API_SECRET = ''


SYMBOL = "BTCUSDT"
BASE_BALANCE = 100
TIMEFRAME = '5m'

PATH_DOWNLOAD_DATA = 'download_data'
PATH_FILE_DOWNLOAD = f"{PATH_DOWNLOAD_DATA}/{SYMBOL}_{TIMEFRAME}.json"

#RSI
RSI_PERIOD = 14
RSI_OVERBOUGHT = 70
RSI_OVERSOLD = 30
